name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: rzx5678
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: rzx5678/publish-packages/game
          tag_with_sha: true
